// <auto-generated />
using System;
using AtmAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AtmAPI.Data.Migrations
{
    [DbContext(typeof(AtmContext))]
    [Migration("20221215121658_AddColInClass")]
    partial class AddColInClass
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AtmAPI.Models.Entities.Absence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("AbsenceDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Reasons")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("StudentId");

                    b.ToTable("Absences");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "ranged_attack",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "melee_fight",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "body_movement",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "vehicle",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "mindset",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "criminal_exploration",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "personal_neat",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "basic",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "human_interaction",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "technology",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        });
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("Available")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<bool>("EnableAutomation")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxLearner")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Placement")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.ClassLecturer", b =>
                {
                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("LecturerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ClassId", "LecturerId");

                    b.HasIndex("LecturerId");

                    b.ToTable("ClassLecturers");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.ExternalInstitution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PassCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkillIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ExternalInstitutions");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.ExternalInstitutionStudent", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("ExternalInstitutionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("StudentId", "ExternalInstitutionId");

                    b.HasIndex("ExternalInstitutionId");

                    b.ToTable("ExternalInstitutionStudents");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Lecturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Code")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComputedColumnSql("CONCAT(\r\n			'ATL',\r\n			CAST(\r\n				SUBSTRING(\r\n					CONVERT(VARCHAR, [CreatedAt], 111),\r\n					0,\r\n					CHARINDEX('/', CONVERT(VARCHAR, [CreatedAt], 111))\r\n				) AS INTEGER\r\n			) % 1000,\r\n			'.',\r\n			RIGHT('000000' + CAST([Id] % 1000000 AS NVARCHAR), 6)\r\n		)", true);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.ToTable("Lecturers");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Operator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Code")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComputedColumnSql("CONCAT(\r\n			'ATO',\r\n			CAST(\r\n				SUBSTRING(\r\n					CONVERT(VARCHAR, [CreatedAt], 111),\r\n					0,\r\n					CHARINDEX('/', CONVERT(VARCHAR, [CreatedAt], 111))\r\n				) AS INTEGER\r\n			) % 1000,\r\n			'.',\r\n			RIGHT('000000' + CAST([Id] % 1000000 AS NVARCHAR), 6)\r\n		)", true);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Operators");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("InitialSlotId")
                        .HasColumnType("int");

                    b.Property<int>("SlotId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("SlotId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "pistol",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "rifle",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "sniper_rifle",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "taekwondo",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "karatedo",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "melee_combat",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "running",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "swimming",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "driving",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "piloting",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "thinking_out_of_the_box",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "critical_thinking",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "problem_solving",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "planning",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "calming",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "leadership",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "investigate",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "judgment",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "details_inspecting",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "tracking",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "tracing",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "visibility",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "adaptability",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "stealing",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "first_aid",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "collaboration",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "communication",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "interviewing",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "interrogation",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "convince",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "networking",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "security",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Name = "computing",
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        });
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.SkillReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Editable")
                        .HasColumnType("bit");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId");

                    b.ToTable("SkillReports");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Slot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndAt")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("StartAt")
                        .HasColumnType("time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("DayOfWeek", "StartAt", "EndAt")
                        .IsUnique();

                    b.ToTable("Slots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            DayOfWeek = 1,
                            EndAt = new TimeSpan(0, 10, 0, 0, 0),
                            StartAt = new TimeSpan(0, 8, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            DayOfWeek = 1,
                            EndAt = new TimeSpan(0, 12, 0, 0, 0),
                            StartAt = new TimeSpan(0, 10, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            DayOfWeek = 1,
                            EndAt = new TimeSpan(0, 15, 0, 0, 0),
                            StartAt = new TimeSpan(0, 13, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            DayOfWeek = 1,
                            EndAt = new TimeSpan(0, 17, 0, 0, 0),
                            StartAt = new TimeSpan(0, 15, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            DayOfWeek = 2,
                            EndAt = new TimeSpan(0, 10, 0, 0, 0),
                            StartAt = new TimeSpan(0, 8, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            DayOfWeek = 2,
                            EndAt = new TimeSpan(0, 12, 0, 0, 0),
                            StartAt = new TimeSpan(0, 10, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            DayOfWeek = 2,
                            EndAt = new TimeSpan(0, 15, 0, 0, 0),
                            StartAt = new TimeSpan(0, 13, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            DayOfWeek = 2,
                            EndAt = new TimeSpan(0, 17, 0, 0, 0),
                            StartAt = new TimeSpan(0, 15, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            DayOfWeek = 3,
                            EndAt = new TimeSpan(0, 10, 0, 0, 0),
                            StartAt = new TimeSpan(0, 8, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            DayOfWeek = 3,
                            EndAt = new TimeSpan(0, 12, 0, 0, 0),
                            StartAt = new TimeSpan(0, 10, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            DayOfWeek = 3,
                            EndAt = new TimeSpan(0, 15, 0, 0, 0),
                            StartAt = new TimeSpan(0, 13, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            DayOfWeek = 3,
                            EndAt = new TimeSpan(0, 17, 0, 0, 0),
                            StartAt = new TimeSpan(0, 15, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            DayOfWeek = 4,
                            EndAt = new TimeSpan(0, 10, 0, 0, 0),
                            StartAt = new TimeSpan(0, 8, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            DayOfWeek = 4,
                            EndAt = new TimeSpan(0, 12, 0, 0, 0),
                            StartAt = new TimeSpan(0, 10, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            DayOfWeek = 4,
                            EndAt = new TimeSpan(0, 15, 0, 0, 0),
                            StartAt = new TimeSpan(0, 13, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            DayOfWeek = 4,
                            EndAt = new TimeSpan(0, 17, 0, 0, 0),
                            StartAt = new TimeSpan(0, 15, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            DayOfWeek = 5,
                            EndAt = new TimeSpan(0, 10, 0, 0, 0),
                            StartAt = new TimeSpan(0, 8, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            DayOfWeek = 5,
                            EndAt = new TimeSpan(0, 12, 0, 0, 0),
                            StartAt = new TimeSpan(0, 10, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            DayOfWeek = 5,
                            EndAt = new TimeSpan(0, 15, 0, 0, 0),
                            StartAt = new TimeSpan(0, 13, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            DayOfWeek = 5,
                            EndAt = new TimeSpan(0, 17, 0, 0, 0),
                            StartAt = new TimeSpan(0, 15, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            DayOfWeek = 6,
                            EndAt = new TimeSpan(0, 10, 0, 0, 0),
                            StartAt = new TimeSpan(0, 8, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            DayOfWeek = 6,
                            EndAt = new TimeSpan(0, 12, 0, 0, 0),
                            StartAt = new TimeSpan(0, 10, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            DayOfWeek = 6,
                            EndAt = new TimeSpan(0, 15, 0, 0, 0),
                            StartAt = new TimeSpan(0, 13, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            CreatedBy = "system",
                            DayOfWeek = 6,
                            EndAt = new TimeSpan(0, 17, 0, 0, 0),
                            StartAt = new TimeSpan(0, 15, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 10, 3, 10, 25, 10, 961, DateTimeKind.Utc),
                            UpdatedBy = "system"
                        });
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Code")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComputedColumnSql("CONCAT(\r\n			'ATS',\r\n			CAST(\r\n				SUBSTRING(\r\n					CONVERT(VARCHAR, [CreatedAt], 111),\r\n					0,\r\n					CHARINDEX('/', CONVERT(VARCHAR, [CreatedAt], 111))\r\n				) AS INTEGER\r\n			) % 1000,\r\n			'.',\r\n			RIGHT('000000' + CAST([Id] % 1000000 AS NVARCHAR), 6)\r\n		)", true);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("EQ")
                        .HasColumnType("float");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<double>("IQ")
                        .HasColumnType("float");

                    b.Property<string>("IdentifyNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("ReactionTime")
                        .HasColumnType("float");

                    b.Property<int>("SelfDiscipline")
                        .HasColumnType("int");

                    b.Property<bool>("Sex")
                        .HasColumnType("bit");

                    b.Property<double>("Stamina")
                        .HasColumnType("float");

                    b.Property<double>("Strength")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Absence", b =>
                {
                    b.HasOne("AtmAPI.Models.Entities.Schedule", "Schedule")
                        .WithMany("Absences")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtmAPI.Models.Entities.Student", "Student")
                        .WithMany("Absences")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Class", b =>
                {
                    b.HasOne("AtmAPI.Models.Entities.Skill", "Skill")
                        .WithMany("Classes")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.ClassLecturer", b =>
                {
                    b.HasOne("AtmAPI.Models.Entities.Class", "Class")
                        .WithMany("ClassLecturers")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtmAPI.Models.Entities.Lecturer", "Lecturer")
                        .WithMany("ClassLecturers")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.ExternalInstitutionStudent", b =>
                {
                    b.HasOne("AtmAPI.Models.Entities.ExternalInstitution", "ExternalInstitution")
                        .WithMany("ExternalInstitutionStudents")
                        .HasForeignKey("ExternalInstitutionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AtmAPI.Models.Entities.Student", "Student")
                        .WithMany("ExternalInstitutionStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ExternalInstitution");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Lecturer", b =>
                {
                    b.HasOne("AtmAPI.Models.Entities.Department", "Department")
                        .WithMany("Lecturers")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Schedule", b =>
                {
                    b.HasOne("AtmAPI.Models.Entities.Class", "Class")
                        .WithMany("Schedules")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtmAPI.Models.Entities.Slot", "Slot")
                        .WithMany("Schedules")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("AtmAPI.Models.Entities.ScheduleCheckIn", "ScheduleCheckIns", b1 =>
                        {
                            b1.Property<DateTime>("CheckInDate")
                                .HasColumnType("datetime2");

                            b1.Property<int>("ScheduleId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.HasKey("CheckInDate", "ScheduleId");

                            b1.HasIndex("ScheduleId");

                            b1.ToTable("ScheduleCheckIn");

                            b1.WithOwner("Schedule")
                                .HasForeignKey("ScheduleId");

                            b1.Navigation("Schedule");
                        });

                    b.Navigation("Class");

                    b.Navigation("ScheduleCheckIns");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Skill", b =>
                {
                    b.HasOne("AtmAPI.Models.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.SkillReport", b =>
                {
                    b.HasOne("AtmAPI.Models.Entities.Class", "Class")
                        .WithMany("SkillReports")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtmAPI.Models.Entities.Student", "Student")
                        .WithMany("SkillReports")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Class", b =>
                {
                    b.Navigation("ClassLecturers");

                    b.Navigation("Schedules");

                    b.Navigation("SkillReports");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Department", b =>
                {
                    b.Navigation("Lecturers");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.ExternalInstitution", b =>
                {
                    b.Navigation("ExternalInstitutionStudents");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Lecturer", b =>
                {
                    b.Navigation("ClassLecturers");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Schedule", b =>
                {
                    b.Navigation("Absences");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Skill", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Slot", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Student", b =>
                {
                    b.Navigation("Absences");

                    b.Navigation("ExternalInstitutionStudents");

                    b.Navigation("SkillReports");
                });
#pragma warning restore 612, 618
        }
    }
}
