// <auto-generated />
using System;
using AtmAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AtmAPI.Data.Migrations
{
    [DbContext(typeof(AtmContext))]
    [Migration("20220918044624_AddEntityScheduleCheckIn")]
    partial class AddEntityScheduleCheckIn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AtmAPI.Models.Entities.Absence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("AbsenceDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Reasons")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("StudentId");

                    b.ToTable("Absences");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("Available")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<bool>("EnableAutomation")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaxLearner")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Placement")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("SkillId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.ClassLecturer", b =>
                {
                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("LecturerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ClassId", "LecturerId");

                    b.HasIndex("LecturerId");

                    b.ToTable("ClassLecturers");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Lecturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Code")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComputedColumnSql("CONCAT(\r\n			'ATL',\r\n			CAST(\r\n				SUBSTRING(\r\n					CONVERT(VARCHAR, [CreatedAt], 111),\r\n					0,\r\n					CHARINDEX('/', CONVERT(VARCHAR, [CreatedAt], 111))\r\n				) AS INTEGER\r\n			) % 1000,\r\n			'.',\r\n			RIGHT('000000' + CAST([Id] % 1000000 AS NVARCHAR), 6)\r\n		)", true);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.ToTable("Lecturers");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Operator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Code")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComputedColumnSql("CONCAT(\r\n			'ATO',\r\n			CAST(\r\n				SUBSTRING(\r\n					CONVERT(VARCHAR, [CreatedAt], 111),\r\n					0,\r\n					CHARINDEX('/', CONVERT(VARCHAR, [CreatedAt], 111))\r\n				) AS INTEGER\r\n			) % 1000,\r\n			'.',\r\n			RIGHT('000000' + CAST([Id] % 1000000 AS NVARCHAR), 6)\r\n		)", true);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Operators");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("InitialSlotId")
                        .HasColumnType("int");

                    b.Property<int>("SlotId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("SlotId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.SkillCategory", b =>
                {
                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("SkillId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("SkillCategories");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.SkillReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Editable")
                        .HasColumnType("bit");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId");

                    b.ToTable("SkillReports");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Slot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndAt")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("StartAt")
                        .HasColumnType("time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("DayOfWeek", "StartAt", "EndAt")
                        .IsUnique();

                    b.ToTable("Slots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5058),
                            CreatedBy = "system",
                            DayOfWeek = 1,
                            EndAt = new TimeSpan(0, 10, 0, 0, 0),
                            StartAt = new TimeSpan(0, 8, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5061),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5070),
                            CreatedBy = "system",
                            DayOfWeek = 1,
                            EndAt = new TimeSpan(0, 12, 0, 0, 0),
                            StartAt = new TimeSpan(0, 10, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5071),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5072),
                            CreatedBy = "system",
                            DayOfWeek = 1,
                            EndAt = new TimeSpan(0, 15, 0, 0, 0),
                            StartAt = new TimeSpan(0, 13, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5072),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5074),
                            CreatedBy = "system",
                            DayOfWeek = 1,
                            EndAt = new TimeSpan(0, 17, 0, 0, 0),
                            StartAt = new TimeSpan(0, 15, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5074),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5075),
                            CreatedBy = "system",
                            DayOfWeek = 2,
                            EndAt = new TimeSpan(0, 10, 0, 0, 0),
                            StartAt = new TimeSpan(0, 8, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5076),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5085),
                            CreatedBy = "system",
                            DayOfWeek = 2,
                            EndAt = new TimeSpan(0, 12, 0, 0, 0),
                            StartAt = new TimeSpan(0, 10, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5085),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5086),
                            CreatedBy = "system",
                            DayOfWeek = 2,
                            EndAt = new TimeSpan(0, 15, 0, 0, 0),
                            StartAt = new TimeSpan(0, 13, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5087),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5088),
                            CreatedBy = "system",
                            DayOfWeek = 2,
                            EndAt = new TimeSpan(0, 17, 0, 0, 0),
                            StartAt = new TimeSpan(0, 15, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5088),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5089),
                            CreatedBy = "system",
                            DayOfWeek = 3,
                            EndAt = new TimeSpan(0, 10, 0, 0, 0),
                            StartAt = new TimeSpan(0, 8, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5090),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5092),
                            CreatedBy = "system",
                            DayOfWeek = 3,
                            EndAt = new TimeSpan(0, 12, 0, 0, 0),
                            StartAt = new TimeSpan(0, 10, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5093),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5094),
                            CreatedBy = "system",
                            DayOfWeek = 3,
                            EndAt = new TimeSpan(0, 15, 0, 0, 0),
                            StartAt = new TimeSpan(0, 13, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5094),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5095),
                            CreatedBy = "system",
                            DayOfWeek = 3,
                            EndAt = new TimeSpan(0, 17, 0, 0, 0),
                            StartAt = new TimeSpan(0, 15, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5096),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5097),
                            CreatedBy = "system",
                            DayOfWeek = 4,
                            EndAt = new TimeSpan(0, 10, 0, 0, 0),
                            StartAt = new TimeSpan(0, 8, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5097),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5098),
                            CreatedBy = "system",
                            DayOfWeek = 4,
                            EndAt = new TimeSpan(0, 12, 0, 0, 0),
                            StartAt = new TimeSpan(0, 10, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5099),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5123),
                            CreatedBy = "system",
                            DayOfWeek = 4,
                            EndAt = new TimeSpan(0, 15, 0, 0, 0),
                            StartAt = new TimeSpan(0, 13, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5124),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5128),
                            CreatedBy = "system",
                            DayOfWeek = 4,
                            EndAt = new TimeSpan(0, 17, 0, 0, 0),
                            StartAt = new TimeSpan(0, 15, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5129),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5130),
                            CreatedBy = "system",
                            DayOfWeek = 5,
                            EndAt = new TimeSpan(0, 10, 0, 0, 0),
                            StartAt = new TimeSpan(0, 8, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5131),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5139),
                            CreatedBy = "system",
                            DayOfWeek = 5,
                            EndAt = new TimeSpan(0, 12, 0, 0, 0),
                            StartAt = new TimeSpan(0, 10, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5139),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5141),
                            CreatedBy = "system",
                            DayOfWeek = 5,
                            EndAt = new TimeSpan(0, 15, 0, 0, 0),
                            StartAt = new TimeSpan(0, 13, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5141),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5142),
                            CreatedBy = "system",
                            DayOfWeek = 5,
                            EndAt = new TimeSpan(0, 17, 0, 0, 0),
                            StartAt = new TimeSpan(0, 15, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5142),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5143),
                            CreatedBy = "system",
                            DayOfWeek = 6,
                            EndAt = new TimeSpan(0, 10, 0, 0, 0),
                            StartAt = new TimeSpan(0, 8, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5144),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5145),
                            CreatedBy = "system",
                            DayOfWeek = 6,
                            EndAt = new TimeSpan(0, 12, 0, 0, 0),
                            StartAt = new TimeSpan(0, 10, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5145),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5146),
                            CreatedBy = "system",
                            DayOfWeek = 6,
                            EndAt = new TimeSpan(0, 15, 0, 0, 0),
                            StartAt = new TimeSpan(0, 13, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5147),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5148),
                            CreatedBy = "system",
                            DayOfWeek = 6,
                            EndAt = new TimeSpan(0, 17, 0, 0, 0),
                            StartAt = new TimeSpan(0, 15, 0, 0, 0),
                            UpdatedAt = new DateTime(2022, 9, 18, 4, 46, 23, 482, DateTimeKind.Utc).AddTicks(5148),
                            UpdatedBy = "system"
                        });
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Code")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComputedColumnSql("CONCAT(\r\n			'ATS',\r\n			CAST(\r\n				SUBSTRING(\r\n					CONVERT(VARCHAR, [CreatedAt], 111),\r\n					0,\r\n					CHARINDEX('/', CONVERT(VARCHAR, [CreatedAt], 111))\r\n				) AS INTEGER\r\n			) % 1000,\r\n			'.',\r\n			RIGHT('000000' + CAST([Id] % 1000000 AS NVARCHAR), 6)\r\n		)", true);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Absence", b =>
                {
                    b.HasOne("AtmAPI.Models.Entities.Schedule", "Schedule")
                        .WithMany("Absences")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtmAPI.Models.Entities.Student", "Student")
                        .WithMany("Absences")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Class", b =>
                {
                    b.HasOne("AtmAPI.Models.Entities.Skill", "Skill")
                        .WithMany("Classes")
                        .HasForeignKey("SkillId");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.ClassLecturer", b =>
                {
                    b.HasOne("AtmAPI.Models.Entities.Class", "Class")
                        .WithMany("ClassLecturers")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtmAPI.Models.Entities.Lecturer", "Lecturer")
                        .WithMany("ClassLecturers")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Lecturer", b =>
                {
                    b.HasOne("AtmAPI.Models.Entities.Department", "Department")
                        .WithMany("Lecturers")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Schedule", b =>
                {
                    b.HasOne("AtmAPI.Models.Entities.Class", "Class")
                        .WithMany("Schedules")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtmAPI.Models.Entities.Slot", "Slot")
                        .WithMany("Schedules")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("AtmAPI.Models.Entities.ScheduleCheckIn", "ScheduleCheckIns", b1 =>
                        {
                            b1.Property<DateTime>("CheckInDate")
                                .HasColumnType("datetime2");

                            b1.Property<int>("ScheduleId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.HasKey("CheckInDate", "ScheduleId");

                            b1.HasIndex("ScheduleId");

                            b1.ToTable("ScheduleCheckIn");

                            b1.WithOwner("Schedule")
                                .HasForeignKey("ScheduleId");

                            b1.Navigation("Schedule");
                        });

                    b.Navigation("Class");

                    b.Navigation("ScheduleCheckIns");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.SkillCategory", b =>
                {
                    b.HasOne("AtmAPI.Models.Entities.Category", "Category")
                        .WithMany("SkillCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtmAPI.Models.Entities.Skill", "Skill")
                        .WithMany("SkillCategories")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.SkillReport", b =>
                {
                    b.HasOne("AtmAPI.Models.Entities.Class", "Class")
                        .WithMany("SkillReports")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtmAPI.Models.Entities.Student", "Student")
                        .WithMany("SkillReports")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Category", b =>
                {
                    b.Navigation("SkillCategories");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Class", b =>
                {
                    b.Navigation("ClassLecturers");

                    b.Navigation("Schedules");

                    b.Navigation("SkillReports");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Department", b =>
                {
                    b.Navigation("Lecturers");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Lecturer", b =>
                {
                    b.Navigation("ClassLecturers");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Schedule", b =>
                {
                    b.Navigation("Absences");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Skill", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("SkillCategories");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Slot", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("AtmAPI.Models.Entities.Student", b =>
                {
                    b.Navigation("Absences");

                    b.Navigation("SkillReports");
                });
#pragma warning restore 612, 618
        }
    }
}
