// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAttendance: typeof import('./src/components/schedule/AAttendance.vue')['default']
    AButton: typeof import('./src/components/AButton.vue')['default']
    AFormKit: typeof import('./src/components/AFormKit.vue')['default']
    ALoading: typeof import('./src/components/loading/ALoading.vue')['default']
    AModal: typeof import('./src/components/AModal.vue')['default']
    APaginationButton: typeof import('./src/components/pagination/APaginationButton.vue')['default']
    APaginationMinimal: typeof import('./src/components/pagination/APaginationMinimal.vue')['default']
    ATooltip: typeof import('./src/components/ATooltip.vue')['default']
    ATransition: typeof import('./src/components/ATransition.vue')['default']
    AttendanceCard: typeof import('./src/components/schedule/AttendanceCard.vue')['default']
    ContextModalCreation: typeof import('./src/components/table/contextModal/ContextModalCreation.vue')['default']
    ContextModalDud: typeof import('./src/components/table/contextModal/ContextModalDud.vue')['default']
    DataTable: typeof import('./src/components/table/DataTable.vue')['default']
    FilterModal: typeof import('./src/components/table/contextModal/FilterModal.vue')['default']
    FormKitSelect: typeof import('./src/components/formkit/FormKitSelect.vue')['default']
    NavLink: typeof import('./src/components/sidebar/navLink/NavLink.vue')['default']
    NavLinkCategory: typeof import('./src/components/sidebar/navLink/NavLinkCategory.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RowCell: typeof import('./src/components/table/rowCell/RowCell.vue')['default']
    RowCellTag: typeof import('./src/components/table/rowCell/RowCellTag.vue')['default']
    RowCellText: typeof import('./src/components/table/rowCell/RowCellText.vue')['default']
    TableUtils: typeof import('./src/components/table/tableUtils/TableUtils.vue')['default']
    TableUtilsFilter: typeof import('./src/components/table/tableUtils/TableUtilsFilter.vue')['default']
    TableUtilsSort: typeof import('./src/components/table/tableUtils/TableUtilsSort.vue')['default']
    TheNavbar: typeof import('./src/components/navbar/TheNavbar.vue')['default']
    TheSidebar: typeof import('./src/components/sidebar/TheSidebar.vue')['default']
    TheUserProfile: typeof import('./src/components/navbar/TheUserProfile.vue')['default']
  }
}
