global using System.ComponentModel.DataAnnotations;
global using System.Linq;
global using System.Net.Mime;
global using System.Reflection;
global using System.Security.Claims;
global using AgentIdentityServer;
global using AgentIdentityServer.Data;
global using AgentIdentityServer.Extensions;
global using AgentIdentityServer.Helpers;
global using AgentIdentityServer.Middlewares;
global using AgentIdentityServer.Models.DTOs.Role;
global using AgentIdentityServer.Models.DTOs.User;
global using AgentIdentityServer.Models.Entities;
global using AutoMapper;
global using Duende.IdentityServer.EntityFramework.DbContexts;
global using Duende.IdentityServer.EntityFramework.Mappers;
global using Duende.IdentityServer.EntityFramework.Storage;
global using Duende.IdentityServer.Events;
global using Duende.IdentityServer.Extensions;
global using Duende.IdentityServer.Models;
global using Duende.IdentityServer.Services;
global using Duende.IdentityServer.Stores;
global using IdentityModel;
global using Microsoft.AspNetCore.Authentication;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.RazorPages;
global using Microsoft.EntityFrameworkCore;
global using Sieve.Models;
global using Sieve.Services;
global using Throw;
global using static AgentIdentityServer.Helpers.EnvVars;
global using static Duende.IdentityServer.IdentityServerConstants;
global using NtsJson = Newtonsoft.Json;
